### PR TITLE
DRAFT: Feature/44/put dashboard pieces together

### LINKED ISSUE #44: Put pieces together to finish dashboard layout
- [x] Add Sidebar
- [x] Add Space Cards
- [x] Add Join/Create Card
- [x] Add Study Charts

image

when hovering over a friends name, a popup should appear. Something like this: 
image

make side drawer collapsable on large viewports 
image

on smaller viewports, make side drawer swipeable.

### PR DESCRIPTION
**Pull request by eden-chan**
closes #44

### CODE REVIEW

**Comment by eden-chan** [comment]
Please save this branch T_T

**Comment by LemonFace0309** [comment]
@eden-chan this branch is way too hard to see the new changes you've made. I think you messed up your commit history somewhere and branched off of a sub branch instead of branching off of main. Make sure for each pr, you have a separate branch that branches off of main and not your own, otherwise we can a mumbo jumbo of code like this. Try doing `git rebase --onto main <old_branch>` to clear up the history. Otherwise it's hard for me to follow what's new and what's in the other pr you submitted.

**Comment by LemonFace0309** [comment]
@eden-chan if you're wondering why vercel isn't deploying, it's because you didn't clear up your merge correctly and you have a ` <<<<<<< HEAD` in your `study-space-demo.js` file

**Review by LemonFace0309 — CHANGES_REQUESTED** [review]
Last thing, I did it for you but please make sure you fill out this column properly. 
image
 That way we the pr gets tracked automatically in the github project tab.

**Comment by eden-chan** [comment]
The study chart, and side bar are incomplete. Should we merge this branch to main first, and then complete #46 and another issue on another branch?

**Comment by LemonFace0309** [comment]
> The study chart, and side bar are incomplete. Should we merge this branch to main first, and then complete #46 and another issue on another branch?

Let's just merge for now. IMO I think it's better to just get the pr out of the way now. I'll make sure to review/edit to make sure code is consistent tonight before merging.

**Review by jimmyygit — COMMENTED** [review]
kinda confused as to why the changes here just look the same as
https://github.com/LemonFace0309/Study-Space/pull/69

but I think the comments I left on that pr should apply here :)

**Pull request merged**
